name: Build ansible-actions container

on:
  pull_request:
    branches: ['*']
  push:
    branches: ['*']

jobs:
  build_push_i:
    name: Build & Push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkout infrastructure repo develop branch
        uses: actions/checkout@v2
        with: 
          repository: ${{ github.repository_owner }}/infrastructure
          fetch-depth: 1
          path: infrastructure
          token: ${{ secrets.CR_PAT }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.CR_USER }}
          password: ${{ secrets.CR_PAT }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/ansible-lint-action:${{ github.sha }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
